# Site settings
title: voidk2's Blog
SEOTitle: 张泽鑫的博客 | voidk2‘s Blog
header-img: img/post-bg-2015.jpg
email: zhangzexindeguge@gmail.com
description: "Every failure is leading towards success."
keyword: "voidk2's Blog, 张泽鑫的博客, zhangzexin, voidk2, iOS, Apple, iPhone"
url: "http://voidk2.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/voidk2/voidk2.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "talk is cheap, show me the code"
sidebar-avatar: /img/about-voidk2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     zhang-ze-xin-19
github_username:    voidk2
facebook_username:  zexinzhang
#jianshu_username:   e71990ada2fd
twitter_username:   voidk2




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
# disqus_username: qiubaiying




# Analytics settings
# Baidu Analytics
# ba_track_id: 

# Google Analytics
# ga_track_id: ''            
# Format: UA-xxxxxx-xx
# ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: 
    {
        title: "私人网盘",
        href: "http://hfuu.gq"
    },{
        title: "个人github",
        href: "http://github.com/voidk2"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    },{
        title: "个人CSDN",
        href: "http://blog.csdn.net/voidk2"
    }
]
